kind: pipeline
type: docker
name: ops-test

steps:
- name: docker build & push
  image: plugins/docker
  when:
    target:
    - production
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: harbor.atompai.com/ops/xb
    #    tags: production-${DRONE_COMMIT}
    tags: production
    registry: harbor.atompai.com
- name: deploy
  image: harbor.atompai.com/ops/nx-k8s-deploy
  when:
    target:
    - production
  environment:
    APP_ENV:
      from_secret: app_env
    K8S_CONFIG:
      from_secret: k8s_config
  commands:
      # - mkdir /root/.kube
     - echo "$APP_ENV" > app_env
       #- echo "$K8S_CONFIG" > /root/.kube/config
     - echo "$APP_ENV"
       #- echo "$K8S_CONFIG"
     - kubectl get ns
     - kubectl delete secret db-user-pass
     - kubectl create secret generic db-user-pass --from-file=app_env
     - kubectl delete -f deployments.yml || kubectl apply -f deployments.yml
      #    - kubectl get pods
      #    - sleep 30
      #    - kubectl get pods
image_pull_secrets:
- k8s_deploy_dockerconfig
trigger:
  event:
  - push
  - promote
  branch:
  - production
