kind: pipeline
type: docker
name: ops-test

environment:
  GOOS: linux
steps:
- name: docker build & push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: harbor.atompai.com/ops/xb
    tags: $${DRONE_COMMIT}

    registry: harbor.atompai.com
    #    dockerfile: path/to/Dockerfile

    #image_pull_secrets:
    #- dockerconfig
trigger:
  event:
  - push
  branch:
  - production
