kind: pipeline
type: docker
name: ops-test

environment:
  GOARCH: amd64
  GOOS: linux
steps:
- name: clone production
  image: harbor.atompai.com/ops/xarc-bitbucket
  #image: alpine/git
  #  settings:
  #    username:
  #      from_secret: username
  #    password:
  #      from_secret: password
  commands:
  - touch abc
  - ls -l  /root/.docker/
  - pwd
  - ls -l
  - ls -l /
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: harbor.atompai.com/ops/xb
    registry: harbor.atompai.com
    #    dockerfile: path/to/Dockerfile
  commands:
  - ls -l

image_pull_secrets:
- dockerconfig
trigger:
  event:
  - push
  branch:
  - production
