kind: pipeline
type: docker
name: ops-test

environment:
    #  harbor-tag: $DRONE_COMMIT
steps:
- name: docker build & push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: harbor.atompai.com/ops/xb
    tags: production-${DRONE_COMMIT}
    registry: harbor.atompai.com
- name: deploy
  image: harbor.atompai.com/ops/nx-k8s-deploy
  commands:
    - kubectl get ns
image_pull_secrets:
- k8s_deploy_dockerconfig
trigger:
  event:
  - push
  branch:
  - production
