kind: pipeline
type: docker
name: ops-production
environment:
  GOOS: linux
  HOME: own

steps:
  #- name: docker build & push
  #  image: plugins/docker
  #  settings:
  #    username:
  #      from_secret: docker_username
  #    password:
  #      from_secret: docker_password
  #    repo: harbor.atompai.com/ops/xb
  #    #    tags: production-${DRONE_COMMIT}
  #    tags: production
  #    registry: harbor.atompai.com
- name: deploy
  image: harbor.atompai.com/ops/nx-k8s-deploy
  environment:
    APP_ENV:
      from_secret: app_env
  commands:
     - echo "$GOOS"
     - echo "$HOME"
     - echo "${HOME}"
     - echo "$${HOME}"
     - echo "$APP_ENV"
     - env
     - echo "$APP_ENV" > app_env
     - kubectl get pods
     - kubectl delete secret db-user-pass
     - kubectl create secret generic db-user-pass --from-file=app_env
     - kubectl apply -f deployments.yml
      #    - kubectl get pods
      #    - sleep 30
      #    - kubectl get pods
image_pull_secrets:
- k8s_deploy_dockerconfig
trigger:
  event:
  - push
  branch:
  - production
