kind: pipeline
type: docker
name: default
   
steps:
- name: clone production
  image: alpine/git
  commands:
  - git clone -b production git@github.com:kurosakisora/hello.git
trigger:
  event:
  - push
