kind: pipeline
type: docker
name: default

environment:
  GOARCH: amd64
  GOOS: linux
steps:
- name: clone production
  image: alpine/git
  commands:
  - echo $GOOS
  - echo $HOME
  - echo $${GOARCH}
  #  - git clone -b production git@github.com:kurosakisora/hello.git
trigger:
  event:
  - push
  branch:
  - production
