kind: pipeline
type: docker
name: ops-test

environment:
    #  harbor-tag: $DRONE_COMMIT
steps:
- name: docker build & push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: harbor.atompai.com/ops/xb
    tags: production-${DRONE_COMMIT}
    #auto_tag_suffix: production-${DRONE_COMMIT}
    registry: harbor.atompai.com
trigger:
  event:
  - push
  branch:
  - production
