kind: pipeline
type: docker
name: ops-test

steps:
- name: docker build & push
  image: plugins/docker
  when:
    target:
    - test
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: harbor.atompai.com/ops/xb
    #    tags: test-${DRONE_COMMIT}
    tags: test
    registry: harbor.atompai.com
- name: deploy
  image: harbor.atompai.com/ops/nx-k8s-deploy:test
  when:
    target:
      include:
        - test
        - test_env
  environment:
    APP_ENV:
      from_secret: app_env_test
  commands:
     - echo "$APP_ENV" > app_env_test
     - kubectl get pods
     - kubectl delete secret db-user-pass || kubectl create secret generic db-user-pass --from-file=app_env_test
     - kubectl delete -f deployments.yml || kubectl apply -f deployments.yml
      #    - kubectl get pods
      #    - sleep 30
      #    - kubectl get pods
image_pull_secrets:
- k8s_deploy_dockerconfig
trigger:
  event:
  - push
  - promote
  branch:
  - test
